# Generated by Django 5.0.3 on 2024-04-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('f_name', models.CharField(max_length=100)),
                ('s_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('sl_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['registered', 'l_name', 'sl_name', 'f_name', 's_name'],
            },
        ),
    ]
