# Generated by Django 5.0.3 on 2024-05-07 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_user_l_name_alter_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['method'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='register_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.register_method'),
        ),
    ]
