# Generated by Django 5.0.3 on 2024-05-07 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_user_register_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register_method',
            options={},
        ),
    ]
