# Generated by Django 5.0.3 on 2024-05-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_register_method_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
