# Generated by Django 5.0.3 on 2024-05-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_user_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
